server:
  build: ./server/
  links:
   - db
  ports:
   - "8000:8000"
  volumes:
   - ./server:/usr/src/app/
  restart: unless-stopped
  environment:
   MONGO_URL: db:27017/
   PORT: 8000
desktop:
  build: ./client-desktop/
  links:
   - server
  ports:
   - "4000:4000"
  volumes:
   - ./client-desktop/src:/usr/src/app/src
  #restart: unless-stopped
  environment:
   SERVER_URL: server:8000
   VIRTUALIZED: "true"
db:
  image: mongo:latest
  restart: unless-stopped
  ports:
   - "27017:27017"